### ISSUE TITLE
Recursor: "Unable to load Lua script from /etc/powerdns/config.lua: No such file or directory"

### ISSUE THREAD

**Issue by InnocentRain** [chrisss404/powerdns#19]
Hey, 
i'm trying to setup the Private Authoritative Server but i can't get the recursor to run. 
I always get the error "Unable to load Lua script from /etc/powerdns/config.lua: No such file or directory" when starting up the container.
Any tips would be appreciated :)

My recursor config:
```
pdns-recursor:
    image: chrisss404/powerdns:latest-recursor
    container_name: pdns-recursor
    restart: unless-stopped
    environment:
      # API
      - RECURSOR_API_READONLY=yes
      - RECURSOR_API_KEY=REDACTED
      # Zones
      - RECURSOR_DNSSEC=off
      - RECURSOR_FORWARD_ZONES={"zone":"REDACTED","forwarders":["pdns-auth"]}
      # Webserver
      - RECURSOR_WEBSERVER=yes
      - RECURSOR_WEBSERVER_PASSWORD=REDACTED
      # Misc
      - RECURSOR_QUIET=no
    sysctls:
      - net.ipv6.route.max_size=16384 
    networks:
      - network-pdns-auth
      - network-pdns-recursor
    ports:
      - "8082:8082/tcp"
```
