### ISSUE TITLE
password authentication failed for user "pdns" and "pda"

### ISSUE THREAD

**Issue by kgnfth** [chrisss404/powerdns#9]
i am trying to run the default config private-authoritative.yml from the readme
and this is what i get
```
authoritative-db_1  | 2021-04-04 18:31:33.562 UTC [42] FATAL:  password authentication failed for user "pdns"
authoritative-db_1  | 2021-04-04 18:31:33.562 UTC [42] DETAIL:  Password does not match for user "pdns".
authoritative-db_1  |   Connection matched pg_hba.conf line 95: "host all all all md5"
authoritative_1     | Waiting for connection to postgres db
admin-db_1          | 2021-04-04 18:31:33.824 UTC [42] FATAL:  password authentication failed for user "pda"
admin-db_1          | 2021-04-04 18:31:33.824 UTC [42] DETAIL:  Password does not match for user "pda".
admin-db_1          |   Connection matched pg_hba.conf line 95: "host all all all md5"
admin_1             | Waiting for connection to postgres db
```

**Comment by kgnfth** [comment]
Ah this works
You have to add some env variables which was not added in the readme example

```yaml
version: '2.1'

services:

  admin:
    image: chrisss404/powerdns:latest-admin
    depends_on:
      - admin-db
      - authoritative
    environment:
      - ADMIN_PDNS_API_KEY=******
      - ADMIN_USER_PASSWORD=******
      - ADMIN_DB_PASS=******
      - ADMIN_DB_USER=pda
      - ADMIN_DB_NAME=pda
      - ADMIN_DB_HOST=admin-db
    networks:
      - admin-db
      - authoritative
    ports:
      - "80:3031"

  admin-db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=pda
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=******
      - POSTGRES_USER=pda
    networks:
      - admin-db

  authoritative:
    image: chrisss404/powerdns:latest-authoritative
    depends_on:
      - authoritative-db
    environment:
      - AUTHORITATIVE_API=yes
      - AUTHORITATIVE_API_KEY=******
      - AUTHORITATIVE_WEBSERVER=yes
      - AUTHORITATIVE_WEBSERVER_PASSWORD=******
      - AUTHORITATIVE_DB_PASS=******
      - AUTHORITATIVE_DB_USER=pdns
      - AUTHORITATIVE_DB_NAME=pdns
      - AUTHORITATIVE_DB_HOST=authoritative-db
    networks:
      authoritative:
        ipv4_address: 172.31.118.118
      authoritative-db:
    ports:
      - "8081:8081/tcp"

  authoritative-db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=pdns
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=******
      - POSTGRES_USER=pdns
    networks:
      - authoritative-db

  dnsdist:
    image: chrisss404/powerdns:latest-dnsdist
    environment:
      - DNSDIST_API_KEY=******
      - DNSDIST_PLAIN=yes
      - DNSDIST_QUIET=no
      - DNSDIST_WEBSERVER=yes
      - DNSDIST_WEBSERVER_PASSWORD=******
    networks:
      - recursor
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
      - "8083:8083/tcp"

  recursor:
    image: chrisss404/powerdns:latest-recursor
    environment:
      - RECURSOR_API_KEY=******
      - RECURSOR_DNSSEC=validate
      - RECURSOR_FORWARD_ZONES=sys=172.31.118.118
      - RECURSOR_QUIET=no
      - RECURSOR_TRUST_ANCHORS=sys=54970 13 1 27efe1c1a790c3cbb43b947d6d6dfac62507097e
      - RECURSOR_WEBSERVER=yes
      - RECURSOR_WEBSERVER_PASSWORD=******
    sysctls:
      - net.ipv6.route.max_size=16384
    networks:
      recursor:
        ipv4_address: 172.31.117.117
      authoritative:
    ports:
      - "8082:8082/tcp"

networks:
  admin-db:
  authoritative:
    ipam:
      driver: default
      config:
        - subnet: "172.31.118.0/24"
  authoritative-db:
  recursor:
    ipam:
      driver: default
      config:
        - subnet: "172.31.117.0/24"
```
